openapi: 3.0.0
info:
  title: App Versions API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: List all regions, environments, and apps
      responses:
        '200':
          description: An overview of all regions, environments, and apps
          content:
            application/json:
              schema:
                type: object
                properties:
                  Regions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Regions'
  /regions:
    post:
      summary: Create a new region
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Regions'
      responses:
        '201':
          description: Region created
    get:
      summary: List all regions
      responses:
        '200':
          description: A list of regions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Regions'
  /regions/{region}/environments:
    post:
      summary: Create a new environment in a region
      parameters:
        - in: path
          name: region
          schema:
            type: string
          required: true
          description: Name of the region
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Environments'
      responses:
        '201':
          description: Environment created
    get:
      summary: List all environments in a region
      parameters:
        - in: path
          name: region
          schema:
            type: string
          required: true
          description: Name of the region
      responses:
        '200':
          description: A list of environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Environments'
  /regions/{region}/environments/{environment}/apps:
    post:
      summary: Create a new app in an environment
      parameters:
        - in: path
          name: region
          schema:
            type: string
          required: true
          description: Name of the region
        - in: path
          name: environment
          schema:
            type: string
          required: true
          description: Name of the environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Apps'
      responses:
        '201':
          description: App created
    get:
      summary: List all apps in an environment
      parameters:
        - in: path
          name: region
          schema:
            type: string
          required: true
          description: Name of the region
        - in: path
          name: environment
          schema:
            type: string
          required: true
          description: Name of the environment
      responses:
        '200':
          description: A list of apps
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Apps'
  /regions/{region}/environments/{environment}/apps/{app}:
    get:
      summary: Get an app by name
      parameters:
        - in: path
          name: region
          schema:
            type: string
          required: true
          description: Name of the region
        - in: path
          name: environment
          schema:
            type: string
          required: true
          description: Name of the environment
        - in: path
          name: app
          schema:
            type: string
          required: true
          description: Name of the app
      responses:
        '200':
          description: Details of an app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apps'
components:
  schemas:
    Regions:
      type: object
      properties:
        Region:
          type: string
        Environments:
          type: array
          items:
            $ref: '#/components/schemas/Environments'
    Environments:
      type: object
      properties:
        Environment:
          type: string
        Apps:
          type: array
          items:
            $ref: '#/components/schemas/Apps'
    Apps:
      type: object
      properties:
        App:
          type: string
        Version:
          type: integer
          format: int32