apiVersion: apps/v1
kind: Deployment
metadata:
  name: vhub
  labels:
    app: vhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vhub
  template:
    metadata:
      labels:
        app: vhub
    spec:
      containers:
      - name: vhub
        image: drewmcl/hub:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5" 
            memory: "256Mi" 
          requests:
            cpu: "0.2" 
            memory: "128Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /app
      volumes:
      - name: config-volume
        configMap:
          name: vhub-config
